import type { Incident } from "./types";
import { NOTIFY_LABELS, SEVERITY_LABELS } from "./types";

function formatWhen(iso: string): string {
  try {
    const d = new Date(iso);
    return d.toLocaleString(undefined, {
      dateStyle: "medium",
      timeStyle: "short",
    });
  } catch {
    return iso;
  }
}

export function buildSummaryText(incident: Incident): string {
  const lines = [
    "INCIDENTPAD SUMMARY",
    "===================",
    `ID: ${incident.id}`,
    `Type: ${incident.type}`,
    `Severity: ${SEVERITY_LABELS[incident.severity]}`,
    `When: ${formatWhen(incident.time)}`,
    `Location: ${incident.location || "—"}`,
    `Trip / Load ID: ${incident.tripLoadId || "—"}`,
    `Notify: ${NOTIFY_LABELS[incident.notify]}`,
    "",
    "Description:",
    incident.description || "—",
    "",
    "Safety checklist:",
    `- Truck stopped safely: ${incident.checklist.truckStoppedSafely ? "Yes" : "No"}`,
    `- Photos noted: ${incident.checklist.photosNoted ? "Yes" : "No"}`,
    `- Police contacted: ${incident.checklist.policeContacted ? "Yes" : "No"}`,
    "",
    `Filed: ${formatWhen(incident.createdAt)}`,
    "Generated by IncidentPad · RoadStar Hackathon 2026",
  ];
  return lines.join("\n");
}

export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    if (navigator.clipboard && window.isSecureContext) {
      await navigator.clipboard.writeText(text);
      return true;
    }
  } catch {
    // fall through
  }

  try {
    const ta = document.createElement("textarea");
    ta.value = text;
    ta.setAttribute("readonly", "");
    ta.style.position = "fixed";
    ta.style.left = "-9999px";
    ta.style.top = "0";
    document.body.appendChild(ta);
    ta.select();
    ta.setSelectionRange(0, ta.value.length);
    const ok = document.execCommand("copy");
    document.body.removeChild(ta);
    return ok;
  } catch {
    return false;
  }
}
